# Generated by Django 5.0.3 on 2024-03-28 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planetarium_service", "0002_alter_astronomyshow_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="astronomyshow",
            name="themes",
            field=models.ManyToManyField(to="planetarium_service.showtheme"),
        ),
        migrations.RemoveField(
            model_name="astronomyshow",
            name="description",
        ),
        migrations.AddField(
            model_name="astronomyshow",
            name="description",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
