# Generated by Django 5.0.3 on 2024-03-28 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("planetarium_service", "0003_astronomyshow_themes_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="groups",
            field=models.ManyToManyField(
                related_name="custom_user_groups", to="auth.group"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="user_permissions",
            field=models.ManyToManyField(
                related_name="custom_user_permissions", to="auth.permission"
            ),
        ),
    ]
