# Generated by Django 5.0.3 on 2024-03-28 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("planetarium_service", "0004_alter_customuser_groups_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ticket",
            options={"ordering": ("row", "seat")},
        ),
        migrations.AlterUniqueTogether(
            name="ticket",
            unique_together={("show_session", "reservation", "row", "seat")},
        ),
    ]
